#!/bin/sh -e
inetd=`grep "^inetd=" /etc/webmin/miniserv.conf 2>/dev/null | sed -e 's/inetd=//g'`
if [ "$1" = "upgrade" ]; then
    # Upgrading the package, so stop the old webmin properly
    if [ "$inetd" != "1" ]; then
        /etc/init.d/webmin stop >/dev/null 2>&1 </dev/null
    fi
fi

cd /usr/share/webmin
config_dir=/etc/webmin
var_dir=/var/webmin
perl=/usr/bin/perl

# collect info from existing miniserv.conf (if it exists)
if [ -f "$config_dir/miniserv.conf" ]; then
    # load existing conf as vars; workaround fact that they're unquoted
    cat $config_dir/miniserv.conf | sed 's|=\(.*\)|="\1"|g' > /tmp/.webmin_miniserv.conf
    . /tmp/.webmin_miniserv.conf
    rm -f /tmp/.webmin_miniserv.conf
fi

WEBMIN_PORT=${WEBMIN_PORT:=10000}

# use vars from existing conf where relevant
login=root
port=${port:-$WEBMIN_PORT}
host=$(hostname)
autoos=3
if [ -z "$ssl" ]; then
    ssl=
else
    ssl=${ssl:-1}
fi
atboot=0
nochown=1
autothird=1
noperlpath=
nouninstall=1
nostart=1

if [ -r /etc/shadow ]; then
    crypt=x
else
    crypt=`grep "^root:" /etc/passwd | cut -f 2 -d :`
fi

export config_dir var_dir perl autoos port login crypt host ssl nochown autothird noperlpath nouninstall nostart allow atboot
./setup.sh >/tmp/.webmin/webmin-setup.out 2>&1

exit_code=0
grep sudo= /etc/webmin/miniserv.conf >/dev/null 2>&1 || exit_code="$?"
if [ "$exit_code" = 1 ]; then
    # Allow sudo-based logins for Ubuntu
    echo sudo=1 >>/etc/webmin/miniserv.conf
fi

rm -f /var/lock/subsys/webmin

cat >/etc/webmin/uninstall.sh <<EOFF
#!/bin/sh
printf "Are you sure you want to uninstall Webmin? (y/n) : "
read answer
printf "\n"
if [ "\$answer" = "y" ]; then
    echo "Removing Webmin package .."
    dpkg --remove webmin
    echo "Done!"
fi
EOFF
chmod +x /etc/webmin/uninstall.sh

#DEBHELPER#

