#!/bin/sh
inetd=`grep "^inetd=" /etc/webmin/miniserv.conf 2>/dev/null | sed -e 's/inetd=//g'`
if [ "$1" = "upgrade" ]; then
	# Upgrading the package, so stop the old webmin properly
	if [ "$inetd" != "1" ]; then
		/etc/init.d/webmin stop >/dev/null 2>&1 </dev/null
	fi
fi

cd /usr/share/webmin
config_dir=/etc/webmin
var_dir=/var/webmin
perl=/usr/bin/perl

set ${WEBMIN_PORT:=10000}

login=root
port=$WEBMIN_PORT
host=`hostname`
autoos=3
ssl=1
atboot=0
nochown=1
autothird=1
noperlpath=
nouninstall=1
nostart=1

if [ -r /etc/shadow ]; then
	crypt=x
else
	crypt=`grep "^root:" /etc/passwd | cut -f 2 -d :`
fi

export config_dir var_dir perl autoos port login crypt host ssl nochown autothird noperlpath nouninstall nostart allow atboot
./setup.sh >/tmp/.webmin/webmin-setup.out 2>&1

exit_code=0
grep sudo= /etc/webmin/miniserv.conf >/dev/null 2>&1 || exit_code="$?"
if [ "$exit_code" = 1 ]; then
    # Allow sudo-based logins for Ubuntu
    echo sudo=1 >>/etc/webmin/miniserv.conf
fi

rm -f /var/lock/subsys/webmin

cat >/etc/webmin/uninstall.sh <<EOFF
#!/bin/sh
printf "Are you sure you want to uninstall Webmin? (y/n) : "
read answer
printf "\n"
if [ "\$answer" = "y" ]; then
	echo "Removing Webmin package .."
	dpkg --remove webmin
	echo "Done!"
fi
EOFF
chmod +x /etc/webmin/uninstall.sh

#DEBHELPER#

